#include <tagdefinitions-private-pch.h>
#include <blofeld_field_type_override.h>

namespace blofeld
{

	TAG_REFERENCE(chud_animation_reference, CHUD_ANIMATION_TAG);
	TAG_REFERENCE(chud_reference, CHUD_TAG);

	TAG_GROUP(chud_animation, CHUD_ANIMATION_TAG)
	{
		{ _field_terminator }
	};

	TAG_GROUP(chud, CHUD_TAG)
	{
		{ _field_terminator }
	};

	TAG_BLOCK(chgd_hud_sounds_block, 65536)
	{
		{ _field_tag_reference, "sound", &global_sound_reference },
		{ _field_long_flags, "latched to", &latched_to_flags_definition },
		{ _field_real, "Scale" },
		{ _field_terminator }
	};

	TAG_REFERENCE_GROUP(chgd_sound_reference, _tag_reference_flag_resolved_by_game)
	{
		SOUND_TAG,
		INVALID_TAG,
	};

	TAG_BLOCK(chgd_hud_attributes_block, 65536)
	{
		{ _field_byte_flags, "resolution flags", &resolution_flags_definition },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "horizontal roll" },
		{ _field_real, "vertical bow" },
		{ _field_real, "inverse horizontal roll" },
		{ _field_real, "inverse vertical bow" },
		{ _field_real, "horizontal roll 2" },
		{ _field_real, "vertical bow 2" },
		{ _field_real, "horizontal twist" },
		{ _field_real, "vertical twist" },
		{ _field_real, "horizontal twist 2" },
		{ _field_real, "vertical twist 2" },
		{ _field_real, "vertical scale" },
		{ _field_real, "vertical twist 3" },
		{ _field_real, "horizontal skew" },
		{ _field_real, "vertical flip" },
		{ _field_real, "inverse horizontal skew" },
		{ _field_real, "vertical flip 2" },
		{ _field_real, "hud offset x" },
		{ _field_real, "hud offset y" },
		{ _field_long_integer, "resolution width" },
		{ _field_long_integer, "resolution height" },
		{ _field_real, "motion sensor offset x" },
		{ _field_real, "motion sensor offset y" },
		{ _field_real, "unknown" },
		{ _field_real, "motion sensor radius" },
		{ _field_real, "motion sensor scale" },
		{ _field_long_integer, "unknown" },
		{ _field_long_integer, "unknown" },
		{ _field_long_integer, "unknown" },
		{ _field_long_integer, "unknown" },
		{ _field_long_integer, "unknown" },
		{ _field_long_integer, "unknown" },
		{ _field_long_integer, "unknown" },
		{ _field_long_integer, "unknown" },
		{ _field_real, "horizontal scale" },
		{ _field_real, "vertical scale" },
		{ _field_real, "horizontal stretch" },
		{ _field_real, "vertical stretch" },
		{ _field_real, "notification offset x" },
		{ _field_real, "notification offset y" },
		{ _field_real, "state left/right offset y" },
		{ _field_real, "state center offset y" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "state scale" },
		{ _field_real, "notification scale" },
		{ _field_real, "notification line spacing" },
		{ _field_long_integer, "notification line count modifier" },
		{ _field_terminator }
	};

	TAG_BLOCK(chgd_waypoint_blips_block, 65536)
	{
		{ _field_string_id, "title" },
		{ _field_string_id, "description" },
		{ _field_char_enum, "icon", &icon_enum_definition },
		{ _field_byte_integer, "unknown" },
		{ _field_short_integer, "unknown" },
		{ _field_real_argb_color, "primary color" },
		{ _field_real_argb_color, "secondary color" },
		{ _field_terminator }
	};

	TAG_BLOCK(chgd_hud_globals_block, 65536)
	{
		{ _field_long_enum, "biped", &biped_enum_definition },
		{ _field_real_argb_color, "0 [HUD disabled]" },
		{ _field_real_argb_color, "1 [HUD primary]" },
		{ _field_real_argb_color, "2 [HUD foreground]" },
		{ _field_real_argb_color, "3 [HUD warning]" },
		{ _field_real_argb_color, "4 [neutral reticule]" },
		{ _field_real_argb_color, "5 [hostile reticule]" },
		{ _field_real_argb_color, "6 [friendly reticule]" },
		{ _field_real_argb_color, "7" },
		{ _field_real_argb_color, "8" },
		{ _field_real_argb_color, "9" },
		{ _field_real_argb_color, "10" },
		{ _field_real_argb_color, "11" },
		{ _field_real_argb_color, "12" },
		{ _field_real_argb_color, "13" },
		{ _field_real_argb_color, "14" },
		{ _field_real_argb_color, "15" },
		{ _field_real_argb_color, "16" },
		{ _field_real_argb_color, "17" },
		{ _field_real_argb_color, "18" },
		{ _field_real_argb_color, "19" },
		{ _field_real_argb_color, "20" },
		{ _field_real_argb_color, "21" },
		{ _field_real_argb_color, "22" },
		{ _field_real_argb_color, "23" },
		{ _field_real_argb_color, "24" },
		{ _field_real_argb_color, "25" },
		{ _field_real_argb_color, "26" },
		{ _field_real_argb_color, "27" },
		{ _field_real_argb_color, "28" },
		{ _field_real_argb_color, "29" },
		{ _field_real_argb_color, "30" },
		{ _field_real_argb_color, "31" },
		{ _field_data, "32" },
		{ _field_data, "33" },
		{ _field_data, "34" },
		{ _field_data, "35" },
		{ _field_data, "36" },
		{ _field_data, "37" },
		{ _field_data, "38" },
		{ _field_data, "39" },
		{ _field_data, "40" },
		{ _field_data, "41" },
		{ _field_real, "blip above threshold max" },
		{ _field_real, "blip above threshold min" },
		{ _field_real, "blip below threshold min" },
		{ _field_real, "blip below threshold max" },
		{ _field_block, "HUD attributes", &chgd_hud_attributes_block_block },
		{ _field_block, "HUD sounds", &chgd_hud_sounds_block_block },
		{ _field_pad, "unknown", 4 },
		{ _field_tag_reference, "unknown", &global_sound_reference },
		{ _field_tag_reference, "frag grenade swap sound", &global_sound_reference },
		{ _field_tag_reference, "plasma grenade swap sound", &global_sound_reference },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_tag_reference, "damage microtexture", &global_bitmap_reference },
		{ _field_real, "microtexture tile scale" },
		{ _field_real, "microtexture screen fraction" },
		{ _field_real, "microtexture inner intensity" },
		{ _field_real, "microtexture center screen fraction" },
		{ _field_real, "microtexture outer intensity" },
		{ _field_tag_reference, "unknown", &global_bitmap_reference },
		{ _field_tag_reference, "directional arrow", &global_bitmap_reference },
		{ _field_tag_reference, "directional fast forward arrow", &global_bitmap_reference },
		{ _field_tag_reference, "unknown", &global_bitmap_reference },
		{ _field_tag_reference, "unknown", &global_bitmap_reference },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_data, "unknown" },
		{ _field_tag_reference, "waypoints", &global_bitmap_reference },
		{ _field_tag_reference, "scoreboard HUD", &chud_reference },
		{ _field_tag_reference, "uber scoreboard HUD", &chud_reference },
		{ _field_tag_reference, "metagame scoreboard HUD", &chud_reference },
		{ _field_tag_reference, "survival scoreboard HUD", &chud_reference },
		{ _field_tag_reference, "theater HUD", &chud_reference },
		{ _field_tag_reference, "forge HUD", &chud_reference },
		{ _field_tag_reference, "HUD strings", &global_multilingual_unicode_string_list_reference },
		{ _field_tag_reference, "medals", &global_bitmap_reference },
		{ _field_tag_reference, "medal HUD animation", &chud_animation_reference },
		{ _field_tag_reference, "cortana channel", &unknown_reference },
		{ _field_tag_reference, "unknown", &unknown_reference },
		{ _field_tag_reference, "unknown", &unknown_reference },
		{ _field_tag_reference, "tracker noise flash response", &unknown_reference },
		{ _field_tag_reference, "tracker noise flash sound", &unknown_reference },
		{ _field_real, "grenade scematics spacing" },
		{ _field_real, "equipment scematic offset y" },
		{ _field_real, "dual equipment scematic offset y" },
		{ _field_real, "unknown equipment related" },
		{ _field_real, "unknown equipment related" },
		{ _field_real, "scoreboard leader offset y" },
		{ _field_real, "unknown" },
		{ _field_real, "waypoint scale" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real_argb_color, "color" },
		{ _field_real, "minor threshold" },
		{ _field_real, "major threshold" },
		{ _field_real, "critical threshold" },
		{ _field_data, "function" },
		{ _field_data, "function" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real_argb_color, "color" },
		{ _field_real, "minor threshold" },
		{ _field_real, "major threshold" },
		{ _field_real, "critical threshold" },
		{ _field_data, "function" },
		{ _field_data, "function" },
		{ _field_block, "waypoint blips", &chgd_waypoint_blips_block_block },
		{ _field_terminator }
	};

	TAG_BLOCK(chgd_shaders_block, 65536)
	{
		{ _field_tag_reference, "vertex shader", & global_vertex_shader_reference },
		{ _field_tag_reference, "pixel shader", &global_pixel_shader_reference },
		{ _field_terminator }
	};

	TAG_BLOCK(chgd_unknown_block, 65536)
	{
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_terminator }
	};

	TAG_BLOCK(chgd_player_training_data_block, 65536)
	{
		{ _field_string_id, "Display String" },
		{ _field_short_integer, "Max Display Time" },
		{ _field_short_integer, "Display Count" },
		{ _field_short_integer, "Disappear Delay" },
		{ _field_short_integer, "Redisplay Delay" },
		{ _field_real, "Display Delay" },
		{ _field_word_flags, "flags", &player_training_flags_definition },
		{ _field_short_integer, "Unknown" },
		{ _field_terminator }
	};

	TAG_BLOCK(chgd_state_triggers_block, 65536)
	{
		{ _field_long_integer, "trigger index" },
		{ _field_string, "type" },
		{ _field_terminator }
	};

	TAG_REFERENCE(unknown_reference);

	TAG_GROUP_FROM_BLOCK(chud_globals, CHUD_GLOBALS_TAG, chgd_block_block);
	TAG_BLOCK_FROM_STRUCT(chgd_block, 1, chgd_struct_definition_struct_definition);
	TAG_STRUCT(chgd_struct_definition)
	{
		{ _field_block, "hud globals", &chgd_hud_globals_block_block },
		{ _field_block, "shaders", &chgd_shaders_block_block },
		{ _field_block, "unknown", &chgd_unknown_block_block },
		{ _field_block, "player training data", &chgd_player_training_data_block_block },
		{ _field_tag_reference, "start menu emblems", &global_bitmap_reference },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_real, "campaign medal scale" },
		{ _field_real, "campaign medal spacing" },
		{ _field_real, "campaign medal offset x" },
		{ _field_real, "campaign medal offset y" },
		{ _field_real, "metagame scoreboard top y" },
		{ _field_real, "metagame scoreboard spacing" },
		{ _field_tag_reference, "unknown", &unknown_reference },
		{ _field_long_integer, "unknown@" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_real, "medium sensor blip scale" },
		{ _field_real, "small sensor blip scale" },
		{ _field_real, "large sensor blip scale" },
		{ _field_real, "vehicle sensor range" },
		{ _field_real, "sensor angle" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_data, "unknown" },
		{ _field_data, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_tag_reference, "motion sensor triangulation field", &global_bitmap_reference },
		{ _field_tag_reference, "motion sensor blip", &global_bitmap_reference },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_real, "unknown" },
		{ _field_tag_reference, "unknown", &unknown_reference },
		{ _field_long_integer, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_long_integer, "unknown" },
		{ _field_real, "unknown" },
		{ _field_long_integer, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_long_integer, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_long_integer, "unknown" },
		{ _field_long_integer, "unknown" },
		{ _field_real, "unknown" },
		{ _field_long_integer, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_long_integer, "unknown" },
		{ _field_real, "unknown" },
		{ _field_long_integer, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "alpha?" },
		{ _field_real, "r?" },
		{ _field_real, "g?" },
		{ _field_real, "b?" },
		{ _field_real, "unknown" },
		{ _field_long_integer, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_long_integer, "unknown" },
		{ _field_long_integer, "unknown" },
		{ _field_real, "unknown" },
		{ _field_long_integer, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_real, "unknown" },
		{ _field_long_integer, "unknown" },
		{ _field_long_integer, "unknown" },
		{ _field_long_integer, "unknown" },
		{ _field_long_integer, "unknown" },
		{ _field_long_integer, "unknown" },
		{ _field_long_integer, "unknown" },
		{ _field_long_integer, "unknown" },
		{ _field_long_integer, "unknown" },
		{ _field_tag_reference, "unknown waypoint bitmap", &global_bitmap_reference },
		{ _field_byte_integer, "sequence index" },
		{ _field_byte_integer, "sprite index" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_tag_reference, "unknown waypoint bitmap", &global_bitmap_reference },
		{ _field_byte_integer, "sequence index" },
		{ _field_byte_integer, "sprite index" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_tag_reference, "unknown waypoint bitmap", &global_bitmap_reference },
		{ _field_byte_integer, "sequence index" },
		{ _field_byte_integer, "sprite index" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_tag_reference, "unknown waypoint bitmap", &global_bitmap_reference },
		{ _field_byte_integer, "sequence index" },
		{ _field_byte_integer, "sprite index" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_tag_reference, "unknown waypoint bitmap", &global_bitmap_reference },
		{ _field_byte_integer, "sequence index" },
		{ _field_byte_integer, "sprite index" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_tag_reference, "unknown waypoint bitmap", &global_bitmap_reference },
		{ _field_byte_integer, "sequence index" },
		{ _field_byte_integer, "sprite index" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_tag_reference, "unknown waypoint bitmap", &global_bitmap_reference },
		{ _field_byte_integer, "sequence index" },
		{ _field_byte_integer, "sprite index" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_tag_reference, "unknown waypoint bitmap", &global_bitmap_reference },
		{ _field_byte_integer, "sequence index" },
		{ _field_byte_integer, "sprite index" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_tag_reference, "unknown waypoint bitmap", &global_bitmap_reference },
		{ _field_byte_integer, "sequence index" },
		{ _field_byte_integer, "sprite index" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_tag_reference, "unknown waypoint bitmap", &global_bitmap_reference },
		{ _field_byte_integer, "sequence index" },
		{ _field_byte_integer, "sprite index" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_tag_reference, "unknown waypoint bitmap", &global_bitmap_reference },
		{ _field_byte_integer, "sequence index" },
		{ _field_byte_integer, "sprite index" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_tag_reference, "unknown waypoint bitmap", &global_bitmap_reference },
		{ _field_byte_integer, "sequence index" },
		{ _field_byte_integer, "sprite index" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_tag_reference, "unknown waypoint bitmap", &global_bitmap_reference },
		{ _field_byte_integer, "sequence index" },
		{ _field_byte_integer, "sprite index" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_tag_reference, "unknown waypoint bitmap", &global_bitmap_reference },
		{ _field_byte_integer, "sequence index" },
		{ _field_byte_integer, "sprite index" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_tag_reference, "unknown waypoint bitmap", &global_bitmap_reference },
		{ _field_byte_integer, "sequence index" },
		{ _field_byte_integer, "sprite index" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_tag_reference, "unknown waypoint bitmap", &global_bitmap_reference },
		{ _field_byte_integer, "sequence index" },
		{ _field_byte_integer, "sprite index" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_tag_reference, "unknown waypoint bitmap", &global_bitmap_reference },
		{ _field_byte_integer, "sequence index" },
		{ _field_byte_integer, "sprite index" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_tag_reference, "unknown waypoint bitmap", &global_bitmap_reference },
		{ _field_byte_integer, "sequence index" },
		{ _field_byte_integer, "sprite index" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_tag_reference, "unknown waypoint bitmap", &global_bitmap_reference },
		{ _field_byte_integer, "sequence index" },
		{ _field_byte_integer, "sprite index" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_tag_reference, "unknown waypoint bitmap", &global_bitmap_reference },
		{ _field_byte_integer, "sequence index" },
		{ _field_byte_integer, "sprite index" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_tag_reference, "unknown waypoint bitmap", &global_bitmap_reference },
		{ _field_byte_integer, "sequence index" },
		{ _field_byte_integer, "sprite index" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_tag_reference, "unknown waypoint bitmap", &global_bitmap_reference },
		{ _field_byte_integer, "sequence index" },
		{ _field_byte_integer, "sprite index" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_tag_reference, "unknown waypoint bitmap", &global_bitmap_reference },
		{ _field_byte_integer, "sequence index" },
		{ _field_byte_integer, "sprite index" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_tag_reference, "unknown waypoint bitmap", &global_bitmap_reference },
		{ _field_byte_integer, "sequence index" },
		{ _field_byte_integer, "sprite index" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_tag_reference, "unknown waypoint bitmap", &global_bitmap_reference },
		{ _field_byte_integer, "sequence index" },
		{ _field_byte_integer, "sprite index" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_tag_reference, "unknown waypoint bitmap", &global_bitmap_reference },
		{ _field_byte_integer, "sequence index" },
		{ _field_byte_integer, "sprite index" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_byte_integer, "unknown" },
		{ _field_block, "state triggers", &chgd_state_triggers_block_block },
		{ _field_terminator }
	};
	TAG_REFERENCE(chud_globals_reference, CHUD_GLOBALS_TAG);

	STRINGS(biped_enum_definition)
	{
		"spartan",
		"elite",
		"monitor",
	};
	STRING_LIST(biped_enum_definition, biped_enum_definition_strings, _countof(biped_enum_definition_strings));
	
	STRINGS(resolution_flags_definition)
	{
		"wide full",
		"standard full",
		"wide/standard half",
		"wide quarter",
		"standard quarter",
		"bit 5",
		"bit 6",
		"bit 7",
	};
	STRING_LIST(resolution_flags_definition, resolution_flags_definition_strings, _countof(resolution_flags_definition_strings));

	STRINGS(latched_to_flags_definition)
	{
		"health recharging",
		"health minor",
		"health major",
		"health critical",
		"health low minor",
		"health low major",
		"health low critical",
		"shield recharging",
		"shield minor",
		"shield major",
		"shield critical",
		"shield minor state",
		"shield major state",
		"shield critical state",
		"rocket locking",
		"rocket locked",
		"missile locking",
		"missile locked",
		"bit 18",
		"bit 19",
		"bit 20",
		"bit 21",
		"bit 22",
		"bit 23",
		"bit 24",
		"bit 25",
		"bit 26",
		"bit 27",
		"bit 28",
		"bit 29",
		"bit 30",
		"bit 31",
	};
	STRING_LIST(latched_to_flags_definition, latched_to_flags_definition_strings, _countof(latched_to_flags_definition_strings));

	STRINGS(icon_enum_definition)
	{
		"null",
		"neutralize",
		"defend",
		"ordnance",
		"interface",
		"scope",
		"recover",
		"arrow",
		"hostile",
		"ammo",
		"recon",
		"structure",
		"blank",
	};
	STRING_LIST(icon_enum_definition, icon_enum_definition_strings, _countof(icon_enum_definition_strings));

	STRINGS(player_training_flags_definition)
	{
		"not in multiplayer",
		"bit 1",
		"bit 2",
		"bit 3",
		"bit 4",
		"bit 5",
		"bit 6",
		"bit 7",
		"bit 8",
		"bit 9",
		"bit 10",
		"bit 11",
		"bit 12",
		"bit 13",
		"bit 14",
		"bit 15",
	};
	STRING_LIST(player_training_flags_definition, player_training_flags_definition_strings, _countof(player_training_flags_definition_strings));
}

